# Utiliza una imagen base adecuada para tu aplicación Flask
FROM python:3.8

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt al directorio de trabajo
COPY requirements.txt .

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# Copia el contenido de la carpeta "app" al directorio de trabajo en el contenedor
COPY app.py /app/
COPY templates/ /app/templates/
COPY requirements.txt /app/

# Expone el puerto en el que se ejecutará la aplicación Flask
EXPOSE 8000

# Comando para iniciar la aplicación Flask
CMD ["python", "app.py"]
