version: '3'
services:
  service-flask-app:
    build:
      context: ./app
      dockerfile: dockerfile
    ports:
      - 8000:8000
    depends_on:
      - service-consumer

  service-consumer:
    build:
      context: ./consumer
      dockerfile: dockerfile
    environment:
      - LOCAL=true
      - PYTHONUNBUFFERED=1


