# Especifica la imagen base
FROM python:3.8

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY requirements.txt /app
COPY app.py /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto que usará la aplicación
EXPOSE 8000

# Ejecuta la aplicación
CMD ["python", "app.py"]
